### ISSUE TITLE
🪙 Badges are not perfectly aligned 

### ISSUE THREAD

**Issue by gopalsasmal100xdev** [gopalsasmal100xdev/next-portfolio#13]
Coding profile badges are not perfectly aligned!

![image](https://github.com/gopalsasmal100xdev/next-portfolio/assets/74035853/05bec805-9905-434c-9ec1-6fd952259624)

**Comment by yordi68** [comment]
![Screenshot from 2024-04-25 06-12-41](https://github.com/gopalsasmal100xdev/next-portfolio/assets/108049153/d4c43f9e-f813-4949-bd46-110a3a5ba2e2)

It seems to be working fine.
It might be because of different screen sizes or have you already fixed the problem?

**Comment by gopalsasmal100xdev** [comment]
In mobile screen badges are not perfectly aligned. so I create pr because of mobile responsive UI.
If you try to fix this issue then it perfectly fine. You can .

The UI will look like in mobile screen 
Before 
📦📦📦
Want
📦
📦
📦

thank you for you interest💖
